TOP = ..
include $(TOP)/configure/CONFIG

IOC = $(TOP)/pvIocApp/

SRC_DIRS += $(IOC)/database

INC += pvDatabase.h

#LIBSRCS += pvDatabase.cpp


#LIBRARY=pvIoc

#pvIoc_LIBS += Com pvData pvAccess

include $(TOP)/configure/RULES

